Principal Component Analysis from scratch

In [1]:
# import packages

import pandas as pd 
import numpy as np
import cvxpy as cp 

In [7]:
# read in file with data

cars = pd.read_excel(r'cars.xlsx', header = 3)
cars = cars.iloc[:,1:]

In [8]:
carsdata = cars.iloc[:,1:].values
carsdata.shape

(32, 11)

In [9]:
# PCA implementation

# 1. Shifting

# calculate the mean of each column
M = np.mean(carsdata.T, axis=1)
# center columns by subtracting column means
C = carsdata - M

# 2. Scaling + 3. Denote X

# calculate standard deviation
SD = np.std(carsdata.T, axis = 1)
# divide columns by standard deviation
X = C/SD
print("X (rounded to two digits)")
print(np.round(X, 2))

# 4. Covariance matrix

# calculate covariance matrix of centered matrix
S = np.cov(X.T)
print("Shat (rounded to two digits)")
print(np.round(S, 2))

# 5. Eigendecomposition

# eigendecomposition of covariance matrix
values, vectors = np.linalg.eig(S)
print("Eigenvectors (rounded to two digits):")
print(np.round(vectors, 2))
print("Eigenvalues (sorted descending and rounded to two digits):")
print(sorted(np.round(values, 2), reverse = True))

# 6./7. Define Q and Z
# project data
Z = vectors.T.dot(X.T)
print("Z matrix (rounded to two digits)")
print(np.round(Z.T, 2))

X (rounded to two digits)
[[ 0.15 -0.11 -0.58 -0.54  0.58 -0.62 -0.79 -0.88  1.21  0.43  0.75]
 [ 0.15 -0.11 -0.58 -0.54  0.58 -0.36 -0.47 -0.88  1.21  0.43  0.75]
 [ 0.46 -1.24 -1.01 -0.8   0.48 -0.93  0.43  1.13  1.21  0.43 -1.14]
 [ 0.22 -0.11  0.22 -0.54 -0.98 -0.    0.9   1.13 -0.83 -0.95 -1.14]
 [-0.23  1.03  1.06  0.42 -0.85  0.23 -0.47 -0.88 -0.83 -0.95 -0.51]
 [-0.34 -0.11 -0.05 -0.62 -1.59  0.25  1.35  1.13 -0.83 -0.95 -1.14]
 [-0.98  1.03  1.06  1.46 -0.73  0.37 -1.14 -0.88 -0.83 -0.95  0.75]
 [ 0.73 -1.24 -0.69 -1.25  0.18 -0.03  1.22  1.13 -0.83  0.43 -0.51]
 [ 0.46 -1.24 -0.74 -0.77  0.61 -0.07  2.87  1.13 -0.83  0.43 -0.51]
 [-0.15 -0.11 -0.52 -0.35  0.61  0.23  0.26  1.13 -0.83  0.43  0.75]
 [-0.39 -0.11 -0.52 -0.35  0.61  0.23  0.6   1.13 -0.83  0.43  0.75]
 [-0.62  1.03  0.37  0.49 -1.    0.89 -0.26 -0.88 -0.83 -0.95  0.12]
 [-0.47  1.03  0.37  0.49 -1.    0.53 -0.14 -0.88 -0.83 -0.95  0.12]
 [-0.82  1.03  0.37  0.49 -1.    0.58  0.09 -0.88 -0.83 -0.95  0.12]
 [-1.63 

In [10]:
percentages = sorted(np.round(100 * (values/np.sum(values)),2), reverse = True)
print("Percentages of variation captured by each PC in ascending order of PC index (rounded to two digits)")
print(percentages)

Percentages of variation captured by each PC in ascending order of PC index (rounded to two digits)
[60.08, 24.1, 5.7, 2.45, 2.03, 1.92, 1.23, 1.12, 0.7, 0.47, 0.2]


In [11]:
cumm_percentages = np.empty(len(percentages))
for i in range(len(percentages)):
    cumm_percentages[i] = sum(percentages[:i+1])
print("Cummulative percentages of variation captured by each PC in ascending order of PC index (rounded to two digits)")
print(cumm_percentages)

Cummulative percentages of variation captured by each PC in ascending order of PC index (rounded to two digits)
[ 60.08  84.18  89.88  92.33  94.36  96.28  97.51  98.63  99.33  99.8
 100.  ]


In [12]:
SDs = sorted(np.round(np.std(Z.T, axis = 0),2), reverse = True)
print("Standard deviation of each PC in ascending order of PC index (rounded to two digits)")
print(SDs)

Standard deviation of each PC in ascending order of PC index (rounded to two digits)
[2.57, 1.63, 0.79, 0.52, 0.47, 0.46, 0.37, 0.35, 0.28, 0.23, 0.15]
